docs_dir: content
extra_css:
- stylesheets/extra.css
markdown_extensions:
- codehilite
- toc:
    permalink: true
    toc_depth: 3
nav:
- Getting started: index.md
- API Reference: api-reference.md
site_name: Deeploy Python Client
theme:
  favicon: img/favicon.ico
  language: en
  logo: img/favicon.ico
  name: material
